{% set name = "luqum" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jurismarches/luqum/archive/refs/tags/{{ version }}.tar.gz
  sha256: 60f8b61dee412319398728fb1b6632a2d3a6d61fc7d71dde7c85e5b7ab92aa74

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - ply >=3.11
    - python >={{ python_min }}

test:
  imports:
    - luqum
    - luqum.elasticsearch
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jurismarches/luqum
  license: Apache-2.0 OR LGPL-3.0-only
  license_file:
    - LICENSE
    - LICENSE.Apache2
    - LICENSE.LGPLv3
  summary: A Lucene query parser generating ElasticSearch queries
  description: |
    luqum (as in LUcene QUery Manipolator) is a tool to parse queries written in
     the Lucene Query DSL and build an abstract syntax tree to inspect, analyze
     or otherwise manipulate search queries. It enables enriching the Lucene
     Query DSL meanings (for example to support nested object searches or have
     particular treatments on some fields), and transform lucene DSL queries to
     native ElasticSearch JSON DSL. Thanks to luqum, your users may continue to
     write queries like: author.last_name:Smith OR author:(age:[25 TO 34] AND
     first_name:John) and you will be able to leverage ElasticSearch query DSL,
     and control the precise meaning of each search terms.
  doc_url: http://luqum.readthedocs.org/en/latest/

extra:
  recipe-maintainers:
    - thewchan
